### ISSUE TITLE
[Feature] WTHIT compatibility

### ISSUE THREAD

**Issue by unilock** [MtcLeo05/BotaniaEditor#2]
I see the mod has a Jade plugin. I think being able to see the range of each flower in a tooltip would be really useful, but unfortunately I don't use Jade. Would you consider adding a WTHIT plugin as well? I imagine the codebases are similar enough.

https://github.com/badasintended/wthit

**Comment by MtcLuna05** [comment]
Thanks for the suggestion! Unfortunately, WTHIT is only for fabric from what I could find and, since the mod is for forge, I can't add compatibility for it.

**Comment by unilock** [comment]
WTHIT supports Fabric, Forge, NeoForge, and Quilt. The source code for each platform can be found in the "platform" directory of WTHIT's source: https://github.com/badasintended/wthit/tree/dev/master/platform

**Comment by MtcLuna05** [comment]
oops, I didn't see that the forge version had another mod page. Just to be sure, since jade and WTHIT use the same exact code, did you see if with WTHIT it works natively even without changes?

Edit. just checked it does in fact not work natively, I'll try fixing it

**Comment by MtcLuna05** [comment]
Implemented, should be available in the latest version once available
