### ISSUE TITLE
Orechid Cost Config Defaults to Lower Than Expected

### ISSUE THREAD

**Issue by DarthDuroq** [MtcLeo05/BotaniaEditor#4]
Just installed the mod and went to look through the configs when I noticed that the default Orechid cost was "5" when it appears to be intended to default to "17500." No prior edits to the config had been done and the config was opened for the first time upon loading up a fresh world.

Edit: Additionally, the Orechid delay for regular worlds appears to default to "2" instead of "100" and the Gaia Mana Spreader appears to default to "2.0" instead of "1.0"

**Comment by MtcLuna05** [comment]
Have you tried deleting the config file and let it regenerate? It seems strange that the default values aren't the correct ones
Edit: I forgot to ask, which version of the mod and minecraft?
Edit 2: Nvm, found the error

**Comment by MtcLuna05** [comment]
Should be fixed when the next version is released
