### ISSUE TITLE
Crash with the newest update.

### ISSUE THREAD

**Issue by Maxi90909** [MtcLeo05/BotaniaEditor#5]
[crash-2024-07-10_19.25.21-client.txt](https://github.com/user-attachments/files/16166987/crash-2024-07-10_19.25.21-client.txt)
 
I get this crash when I update Botania Editor to Version 1.0.7. I don't get this crash on version 1.0.0.

**Comment by MtcLuna05** [comment]
From the crash report the issue seems to be caused by a mod called Dungeon Now Loading. I'll see if there's an incompatibility with the mod itself, but could you try without this mod, to see if the problem is an incompatibility or something broken with Botania Editor itself?

**Comment by Maxi90909** [comment]
I remove canary and then the crash report said create was the problem. I dunno to be honest. I don't have that crash report anymore.

**Comment by MtcLuna05** [comment]
Just to make sure, this happens with the 1.20.1 or the 1.19.2 version?

**Comment by Maxi90909** [comment]
I am playing Version 1.20.1. So that one.

**Comment by MtcLuna05** [comment]
The error only happens when outside the dev environment, that's why I couldn't notice it. I'll see if I find a fix

**Comment by MtcLuna05** [comment]
Fixed it, will upload asap
